# This file contains the settings for DRBOT.
# You can fill it in manually or run first_time_setup.py for an interactive interface.


# ==============
# Authentication
# ==============

# DRBOT needs an account with mod permissions on your sub.
# It's strongly recommended to create a new account instead of using a real human's account.
# You can authenticate in one of two ways:

# 1. Through Reddit
# Use first_time_setup.py to get a refresh token and enter it here.
# (You can do this on another computer if you can't use a browser on this computer.)
refresh_token = ""

# 2. Manually (not recommended)
# This method is less safe as it involves storing the account password in plaintext,
# so don't use it unless you have a good reason.
# You can create a client_id and client_secret at https://www.reddit.com/prefs/apps/
# Choose 'script' as the option and put http://localhost:8080/ as the redirect URI.
username = "" # Don't include u/
password = ""
client_id = ""
client_secret = ""

# The sub to moderate (without r/).
subreddit = ""


# ======
# Points
# ======

# When a user has this many points, the bot will take action.
point_threshold = 12

# How many points does each removal cost?
# For example:
#   point_config = [
#       {id="Some removal reason title", points=3, expires=2},
#       {id="Another one", points=0}
#   ]
# The ID of a removal reason must be its exact title.
# You can optionally set a different expiration time (in months) for each removal reason;
# If you don't it will use the default from below.
point_config = [
    
]

# Number of months before a removal is forgiven and wiped from the record.
# Set to 0 to never expire.
expiration_months = 6

# What should the bot do when a user passes the point threshold?
# 1: notify the mods
# 2: autoban and notify the mods
# 3: autoban silently
autoban_mode = 1



# =======================================================
# ADVANCED SETTINGS BELOW HERE
# (Don't change these unless you want something specific)
# =======================================================



# =======
# Logging
# =======

# Log file name. Leave blank to turn off the logfile (not recommended).
log_file = "data/log.log"

# Minimum log level to print to console / save to file.
# Must be one of CRITICAL, ERROR, WARNING, INFO, DEBUG
console_log_level = "INFO"
file_log_level = "DEBUG"

# Optionally, DRBOT can save PRAW's logging output to a file.
# This records every single request made to the reddit API (which can get big fast).
# It's off by default, but you can turn it on by setting this to a filename like "data/praw.log".
praw_log_file = ""


# =====
# Modes
# =====

# Dry run mode - if you want to test DRBOT without affecting your sub.
# It won't take any actions on Reddit and will log what it would have done instead.
dry_run = false

# Safe mode - do greedy safety checks instead of lazy ones.
# e.g. check for comment re-approval on every operation instead of only periodically and when needed.
# Will significantly slow down the bot and increase the traffic from your bot to reddit.
safe_mode = false

# By default, the bot will not ban mods or track their points.
# You can force it to include mods by setting this to false.
# This may cause permissions issues with your sub - mods can't always ban other mods.
exclude_mods = true

# You can make exceptions for individual removals and give them custom point values
# by putting the point number inside square brackets anywhere in the mod note of the removal, like this:
#   [0]
# This lets you make special exceptions to not count a removal as a strike against a user
# or give extra points for a removal.
# This requires extra requests though, which slows down the bot, so you can turn it off here.
# (If safe mode is active then these requests already happen, so this won't slow things down.)
custom_point_mod_notes = true


# =======
# Storage
# =======

# DRBOT stores its data on an automatically-managed wiki page on your sub.
# You can change the name of the page here.
# Leave it blank if you want everything to be local (not recommended).
wiki_page = "drbot"

# DRBOT also makes periodic local backups just in case things go wrong.
# You can set the filename of the backup here, or leave it blank to turn this off.
local_backup_file = "data/backup.json"


# =========
# Messaging
# =========

# When modmailing you, truncate long comments to this many characters (or set to 0 to disable truncation).
# Warning: if you set this too high, the message may go over the character limit.
modmail_truncate_len = 100

# Whether to send modmail when self-moderation is detected (otherwise it's just logged).
self_moderation_modmail = false

# Whether to send modmail when admin action is detected (otherwise it's just logged).
admin_modmail = true
